[[redirects]]
from = "car-lease/tesla/model-x/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "car-lease/tesla/model-s/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "car-lease/tesla/model-3/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "car-lease/renault/renault-zoe/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "car-lease/mini/mini-electric/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "car-lease/bmw/the-upmarket-bmw-i3-is-a-left-field-choice-in-an-already/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"
